version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd component-processing
      - mvn clean package
      - echo Building the docker image
      - docker build -t compapp .
      - docker tag compapp 156962844638.dkr.ecr.us-west-2.amazonaws.com/romscomp_894462:compapp
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(docker images)
      - docker push 156962844638.dkr.ecr.us-west-2.amazonaws.com/romscomp_894462:compapp
      - echo Writing definition files
      - printf '[{"name":"compapp-container","imageUri":"%s"}]' 156962844638.dkr.ecr.us-west-2.amazonaws.com/romscomp_894462:compapp > taskdefinition.json

artifacts:
  files: component-processing/taskdefinition.json


