version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd service-registry
      - mvn clean package
      - echo Building the docker image
      - docker build -t servapp .
      - docker tag servapp 156962844638.dkr.ecr.us-west-2.amazonaws.com/romsserviceregistry_894462:servapp
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(docker images)
      - docker push 156962844638.dkr.ecr.us-west-2.amazonaws.com/romsserviceregistry_894462:servapp
      - echo Writing definition files
      - printf '[{"name":"servapp-container","imageUri":"%s"}]' 156962844638.dkr.ecr.us-west-2.amazonaws.com/romsserviceregistry_894462:servapp > taskdefinition.json

artifacts:
  files: service-registry/taskdefinition.json


